app = "authify-back"  # Altere para o nome real da sua app no Fly.io

primary_region = "gru"  # Altere para sua região preferida

[build]
  # Usa o Dockerfile da raiz
  dockerfile = "./Dockerfile"

[env]
  PORT = "4000"
  DATABASE_URL = "file:/app/data/dev.db"


[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
